### ISSUE TITLE
AttributeError: 'SpooledTemporaryFile' object has no attribute 'seekable'

### ISSUE THREAD

**Issue by jenskutilek** [fonttools/fonttools#3052]
I'm running a FontTools API on a Flask server.

Uploaded fonts are written by flask to a `SpooledTemporaryFile`. This fails since 15b450e4 because of the file.seekable() test added, which is not supported by `SpooledTemporaryFile`:

```
uwsgi[3581158]: [2023-03-21 11:59:25,093] ERROR in app: Exception on /api/fontinfo [POST]
uwsgi[3581158]: Traceback (most recent call last):
uwsgi[3581158]:   File "/var/www/fonttools/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
uwsgi[3581158]:     return self.finalize_request(rv)
uwsgi[3581158]:   File "/var/www/fonttools/venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
uwsgi[3581158]:     """Dispatches the request and on top of that performs request
uwsgi[3581158]:   File "/var/www/fonttools/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
uwsgi[3581158]:     resp = resource(*args, **kwargs)
uwsgi[3581158]:   File "./app/api_helpers.py", line 28, in decorated_view
uwsgi[3581158]:     return wrapped_function(*args, **kwargs)
uwsgi[3581158]:   File "/var/www/fonttools/venv/lib/python3.9/site-packages/flask/views.py", line 107, in view
uwsgi[3581158]:     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
uwsgi[3581158]:   File "/var/www/fonttools/venv/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
uwsgi[3581158]:     resp = meth(*args, **kwargs)
uwsgi[3581158]:   File "./app/api.py", line 81, in post
uwsgi[3581158]:     font = TTFont(args.file.stream)
uwsgi[3581158]:   File "/var/www/fonttools/venv/lib/python3.9/site-packages/fontTools/ttLib/ttFont.py", line 149, in __init__
uwsgi[3581158]:     if file.seekable():
uwsgi[3581158]: AttributeError: 'SpooledTemporaryFile' object has no attribute 'seekable'
```

**Comment by jenskutilek** [comment]
On second thought, I'm not sure if `hasattr(file, "seekable") and file.seekable():` would have any undesired side effects. `SpooledTemporaryFile` supports `seek()`, as demonstrated by the code before the change, which worked without any issues.

What would happen if we just wrapped `seek()` in a `try ... except` block?

I can't upgrade my server's Python before the next Debian stable is released, but I don't really need the latest FontTools there, so at least there is a workaround.

**Comment by anthrotype** [comment]
actually I don't even remember why we did put that seek(0) in the TTFont constructor.. maybe something to do with TrueType Collections? /cc @behdad
